#!/usr/bin/env ruby

# wrap multi-word arguments in quotes
ARGS = ARGV.map{ |arg| !!(/\s/).match(arg) ? "\"#{arg}\"" : arg }.join(' ')

# does the command look like an explicit force push to master?
def explicit?
  system("echo \"#{ARGS}\" | egrep \"push.*(-f|--force).*(master|production).*\" &> /dev/null") &&
  system("git status &> /dev/null")
end

# if the branch isn't named in the command, check the current branch
def implicit?
  system("echo \"#{ARGS}\" | egrep \"push.*(-f|--force).*\" &> /dev/null") &&
  system("git status &> /dev/null && git branch 2> /dev/null | sed -e \"/^[^*]/d\" | egrep \"master|production\" &> /dev/null")
end

# issue warning and confirm force push
if explicit? || implicit?
  STDOUT.write("\033[00;31mYou are attempting to force push to the master branch!\033[00m\nAre you sure? [yes/no] ")
  if STDIN.gets != "yes\n"
    STDOUT.write("Your git push was aborted.\n")
    exit(1);
  end
end

# pass args to git, or hub if installed
if system('command -v hub &> /dev/null')
  command = 'hub'
else
  command = 'git'
end
command += " #{ARGS}"
exit(system(command))
